read_excel_converter = {
    'PL_PURCH_ORDER_DATA_PT5':{'PO - PO Line No' : int, 
                               'PO - PO Sched Line': int, 
                               'PO - PO Distrib Line' : int,
                               'PO - Req Line No' : int, 
                               'PO - Req Sched No' : int, 
                               'PO - Req Distrib No' : int, 
                               'PO - Hdr Chng Order No' : int,
                               'PO - Hdr Chng Order Seq' : int, 
                               'PO - Line Chng Order Seq' : int, 
                               'PO - RFQ Line No' : int,
                               'PO - PO Hdr Match Process Inst' : int, 
                               'PO - Curr Bid Recv' : int, 
                               'PO - Curr Bid Sent' : int, 
                               'PO - Prev Bid Sent' : int},
    'PL_PURCH_ORDER_DATA_PT6':{'PO - PO Line No' : int, 
                               'PO - PO Sched Line': int, 
                               'PO - PO Distrib Line' : int,
                               'PO - Req Line No' : int, 
                               'PO - Req Sched No' : int, 
                               'PO - Req Distrib No' : int, 
                               'PO - Hdr Chng Order No' : int,
                               'PO - Hdr Chng Order Seq' : int, 
                               'PO - Line Chng Order Seq' : int, 
                               'PO - RFQ Line No' : int,
                               'PO - PO Hdr Match Process Inst' : int, 
                               'PO - Curr Bid Recv' : int, 
                               'PO - Curr Bid Sent' : int, 
                               'PO - Prev Bid Sent' : int},
    'PL_PURCH_ORDER_DATA_PT7':{'PO - PO Line No' : int, 
                               'PO - PO Sched Line': int, 
                               'PO - PO Distrib Line' : int,
                               'PO - Req Line No' : int, 
                               'PO - Req Sched No' : int, 
                               'PO - Req Distrib No' : int, 
                               'PO - Hdr Chng Order No' : int,
                               'PO - Hdr Chng Order Seq' : int, 
                               'PO - Line Chng Order Seq' : int, 
                               'PO - RFQ Line No' : int,
                               'PO - PO Hdr Match Process Inst' : int, 
                               'PO - Curr Bid Recv' : int, 
                               'PO - Curr Bid Sent' : int, 
                               'PO - Prev Bid Sent' : int},
    'PL_VOUCHER_PYMTS_PT7':{'VCH - Voucher Line No' : int, 
                            'VCH - PO Line No' : int,
                            'VCH - PO Line Sched No' : int, 
                            'VCH - PO Distrib Line' : int, 
                            'VCH - Voucher Rcpt Line No' : int, 
                            'VCH - Acctg Period' : int, 
                            'VCH - Vchr Fiscal Year' : int}, 
    'PL_BUYER_BACKLOG':{'BL - Req Sched No' : int,
                        'BL - Req Distrib Line' : int,
                        'ROH - Req Line No' : int},
    'PL_CHNG_ORDER_INSERTS':{'CHG - PO Line No' : int, 
                             'CHG - Chng Order Seq' : int, 
                             'CHG - Change Order Batch' : int, 
                             'CHG - Reason Seq' : int, 
                             'CHG - PO Line Sched No' : int},
    'PL_CNT_ACTIVITY':{'ACTV - Contract Version' : int,
                       'ACTV - Seq Num' : int},
    'PL_PO_PARTICIPATION_DBE':{'DBE - PO Line No' : int,
                               'DBE - PO Line Sched No' : int, 
                               'DBE - PO Distrib Line No' : int, 
                               'DBE - Supplier SeqNum' : int}, 
    'PL_REQUISITION_DATA':{'REQ - Req Line No' : int,
                           'REQ - Req Sched No' : int, 
                           'REQ - Req Distrib Line' : int},
    'PL_PO_ENCUMB_LINE':{'ENC - PO Line No' : int,
                         'ENC - PO Sched Line No':int,
                         'ENC - PO Distrib Line No': int}}







dictionary_header = {'PO':'PO - Query Date',
                     'BL':'BL - Query Date',
                     'ACTV':'ACTV - Query Date',
                     'CTR':'CTR - Query Date',
                     'ACTIVITY':'ACTIVITY - Query Date',
                     'REQ':'REQ - Query Date',
                     'VCH':'VCH - Query Date',
                     'OBS':'OBS - Query Date',
                     'IOH':'IOH - Query Date',
                     'TXN':'TXN - Query Date',
                     'CC':'CC - Query Date'}

#Function for extracting field initials in dictionary_header                                                                                                                                           
def find_col_name(colname):
    if colname in dictionary_header.keys():
        return dictionary_header.get(colname)
    else:
        return "Query Date"